name: Hi there

on: [pull_request, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Annnnnd you broke it, aren't you?"
        pr-message: "What? first time? **gives you a condom** Just don't broke it when you'll be inside"
